- name: Configure the webserver
  hosts: wsrv-prod
  become: True
  vars:
  tasks:
    - name: baptize the server
      hostname:
        name: "{{ servername }}.{{ domain }}"
      notify: restart apache

    - name: get time
      command: date --rfc-3339=seconds
      register: last_run

    - name: disable selinux
      selinux:
        state: disabled
      register: slnx

    - name: restart host
      shell: reboot
      async: 0
      poll: 0
      register: restart_sleeper
      when: slnx.changed

    - name: wait for host to come up
      local_action: wait_for host=wsrv-prod state=started
      when: slnx.changed

  #    - name: wait for host to come up
  #      async_status: jid={{ restart_sleeper.ansible_job_id }}
  #      register: job_result
  #      until: job_result.finished
  #      retries: 30



    - name: install required packages
      yum:
        name: "{{ item }}"
        state: installed
        update_cache: True
      with_items:
        - httpd
        - openssl
        - mod_ssl
        - tree
        - screen
        - vim

    - name: copy apache configuration file
      copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: restart apache

    - name: copy the certificate
      copy:
        src: files/webserver/httpd.crt
        dest: /etc/pki/tls/certs/httpd.crt

    - name: copy the private key
      copy:
        src: files/webserver/httpd.key
        dest: /etc/pki/tls/private/httpd.key

    - name: copy website
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted


