- name: Configure the webserver
  hosts: wsrv
  become: True
  vars:
    servername: "{{ inventory_hostname }}.{{ domain }}"
      
  tasks:

    - name: baptize the server
      hostname:
        name: "{{ servername }}"
      notify: restart apache

    - name: get time
      command: date --rfc-3339=seconds
      register: last_run

    - name: install required packages
      yum:
        name: "{{ item }}"
        state: installed
        update_cache: True
      with_items:
        - libselinux-python
        - httpd
        - openssl
        - mod_ssl
        - links
        - tree
        - screen
        - vim

    - name: disable selinux
      selinux:
        state: disabled
      register: slnx

    - name: restart host
      shell: reboot
      async: 0
      poll: 0
      when: slnx.changed

    - name: wait for host to come up
      local_action: wait_for host=wsrv-prod state=started
      when: slnx.changed

    - name: create the hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts
      notify: restart apache

    - name: copy the certificate
      copy:
        src: files/{{ inventory_hostname }}/localhost.crt
        dest: /etc/pki/tls/certs/localhost.crt
      notify: restart apache

    - name: copy the private key
      copy:
        src: files/{{ inventory_hostname }}/localhost.key
        dest: /etc/pki/tls/private/localhost.key
      notify: restart apache

    - name: copy website
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted


